---
- name: Packer App
  become: true
  hosts: all
  tasks:
    - name: Install Software
      become: true
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - ruby-full
        - ruby-bundler
        - build-essential
