---
- name: Packer DB
  become: true
  hosts: all
  tasks:

    - name: Add key
      become: true
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc
        state: present

    - name: Add repo
      become: true
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
        state: present

    - name: Install db
      become: true
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Install service
      become: true
      systemd: name=mongod enabled=yes
