---

  # db

- name: Configure MongoDB
  hosts: db
  tags: db-tag
  become: true

  vars:
   mongo_bind_ip: 0.0.0.0

  tasks:
   - name: Change mongo config file
     template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
     notify: restart mongod

  handlers:
   - name: restart mongod
     service: name=mongod state=restarted

# app

- name: Configure hosts & deploy application
  hosts: app
  vars:
   db_host: 178.154.201.244
  tasks:
    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
      tags: app-tag

    - name: enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag

  handlers:
  - name: reload puma
    become: true
    systemd: name=puma state=restarted

# deploy app

- name: Deploy App
  hosts: app
  tags: deploy-tag
  tasks:
    - name: Установка пакетов
    #  yum: pkg={{ item }} state=latest
    #  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      become: true
      apt: pkg={{ item }} state=latest
      with_items:
       - git
       - mc
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: restart puma

    - name: bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
